samesystem/graphql_rails

lib/graphql_rails/attribute/attribute_type_parser.rb
lib/graphql_rails/model/configuration.rb
spec/lib/graphql_rails/attribute/attribute_type_parser_spec.rb

This PR allows referencing other models as valid graphql types.
Issue: #22

Refs #22: Allow referencing other models as types.

---

lib/graphql_rails/model/configuration.rb

Ignores `:offset` on `ActiveRecord::Relation` count, to support queries with `:skip` parameter specified in [OpenCRUD](https://www.opencrud.org/#sec-Queries)

Ignore offset in connection 'total' field

---

Gemfile.lock
lib/graphql_rails/type_parser.rb
lib/graphql_rails/version.rb
spec/lib/graphql_rails/type_parser_spec.rb

Currently, in controller, it's only possible to specify single word classes as return type, like `action(:create).returns('User')`, `action(:create).returns('Admin::Order')`, but not `action(:create).returns('SomeUser')`, `action(:create).returns('UserArea::ShopList')`. This PR fixes this issue

Resolve multi word graphql types correctly

---

CHANGELOG.md
lib/graphql_rails/controller/action_hooks_runner.rb
spec/lib/graphql_rails/controller/action_hooks_runner_spec.rb

Currently anonymous hooks (defined with block, and not with method name) are run in wrong context, so it's impossible to call controller methods. For example, this was impossible:
```
class MyController < GraphqlRails::Controller
before_action do
return if current_user.active?
raise UserNotActiveError
end
def current_user
end
end
```

Execute hooks in controller context

---

CHANGELOG.md
lib/graphql_rails.rb
lib/graphql_rails/query_runner.rb
lib/graphql_rails/router.rb
lib/graphql_rails/router/route.rb
spec/lib/graphql_rails/query_runner_spec.rb
spec/lib/graphql_rails/router_spec.rb
spec/spec_helper.rb

This will allow us to remember routes which where defined with Router.draw.
`QueryRunner` uses this default router and allows to simplify rails side controller. It also opens possibility to test real requests in rspec
Solves #93

Add default router and QueryRunner

---

CHANGELOG.md
docs/README.md
docs/components/controller.md
docs/testing/testing.md
lib/graphql_rails/controller/action.rb
lib/graphql_rails/controller/action_configuration.rb
spec/lib/graphql_rails/controller/action_spec.rb
spec/lib/graphql_rails/controller/controller_function_spec.rb

Currently when controller action does not specify return type then this type is guessed based on controller name. For example:
```
class UsersController < GraphqlRails::Controller
action(:index)
action(:show)
end
```
for `index` action it will set return type `[Users!]!` and for show action it will set `User!`.
This model guessing feature is a little bit too magical and also makes GraphqlRails code more complicated then it should.
This PR forces to specify return type for each action and also removes `can_return_nil` method because it affected only guessed types. In other words `action(:index)` will raise exception complaining we should replace it with `action(:index).returns(Something)`

Remove default return type for controller

---

lib/graphql_rails/controller/action_configuration.rb
spec/lib/graphql_rails/controller/configuration_spec.rb

Currently we have a bug when we use multiple action for same controller, and one of action has `options` part. Example:
```ruby
class MyController < GraphqlRails::Controller
action(:something).options(input_format: :original)
action(:something_else)
end
```
the problem is that `action(:something_else)` will also inherits `.options(input_format: :original)`
This PR fixes this issue and also makes `options` method more consistent with other config methods

Do not share options config between actions

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/attributable.rb
lib/graphql_rails/attributes/attribute.rb
lib/graphql_rails/attributes/attribute_name_parser.rb
spec/lib/graphql_rails/attributes/attribute_name_parser_spec.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb

This allows passing `options` flag to attribute defined on the model level. See linked issue #148

Refs #148: Allow changing method name format fom model

---

CHANGELOG.md
lib/graphql_rails/attributes/attribute.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb

Fixes the case where camelize is not used on attribute name, but on GraphQL gem internals it was still expected to be camelized. #149

Fix camelize option forwarding

---

lib/graphql_rails/model/configuration.rb
spec/lib/graphql_rails/model/configuration_spec.rb

When an attribute is being defined as `required` through parameter passing, rather than method chaining, an error gets triggered that prevents schema generation. This is an attempt to fix that issue.

Fix: allow required field in attribute type definition

---

lib/graphql_rails/controller/request.rb
lib/graphql_rails/controller/request/format_errors.rb
spec/lib/graphql_rails/controller/request/format_errors_spec.rb

After updating graphql rails to support Ruby 2.7 and refactoring code base graphql service was changed and it enforced `FormatErrors` service arguments (`ActiveModel::Error`) to be transformed to hash.
This PR fixes it.

Fix graphql errors formatting

---

lib/graphql_rails/model/configurable.rb

Circular dependency still occurs if type name is not cached. Type name should be cached value.

Fix type name caching issue

---

Gemfile.lock
graphql_rails.gemspec
lib/graphql_rails/router/schema_builder.rb

Bumping `graphql` version. Patch in schema is required due to an existing bug in `graphql` gem (https://github.com/rmosolgo/graphql-ruby/pull/2814).

Bump graphql version

---

lib/graphql_rails/attributes/attributable.rb
lib/graphql_rails/attributes/attribute_name_parser.rb
lib/graphql_rails/attributes/type_parseable.rb
lib/graphql_rails/router/schema_builder.rb
spec/lib/graphql_rails/attributes/attribute_name_parser_spec.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb
spec/lib/graphql_rails/attributes/input_attribute_spec.rb
spec/lib/graphql_rails/attributes/type_parser_spec.rb
spec/lib/graphql_rails/controller/action_configuration_spec.rb
spec/lib/graphql_rails/controller/action_spec.rb
spec/lib/graphql_rails/model/configuration_spec.rb

This fixes incorrect type resolutions leading to type mismatch errors.
You should no longer use `GraphQL::STRING_TYPE` in your application, use `GraphQL::Types::String` instead. This is part of `graphql` 11.6->12.4 upgrade which was not done correctly in the initial release of version 1.2.0

Remove deprecated graphql types

---

lib/graphql_rails/attributes/attributable.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb

Fixes attribute type parser.  Instances of `GraphQL::Schema::NonNull` are marked as required, making the schema generation work as expected.

Refs #185: Fix required list type implementation

---

lib/graphql_rails/model/build_connection_type.rb
lib/graphql_rails/model/build_connection_type/count_items.rb
spec/lib/graphql_rails/model/build_connection_type/count_items_spec.rb

Using `nodes` is not correct there, as it takes pagination into account. So you'll always have `total` = maximum entries per page, which will always end up with a single page. Instead, use `items` which is implemented by ActiveRecordConnectionWraper.

Use items instead of nodes as they're pre-paginated

---

.github/workflows/ruby.yml

Repo automation update for ruby 3.0

---

lib/graphql_rails/model/configurable.rb
lib/graphql_rails/model/configuration.rb
lib/graphql_rails/model/input.rb
spec/lib/graphql_rails/model_spec.rb

When using inheritance, parent and child classes same `graphql_type` which is not correct. This PR fixes that issue

Do not inherit parent graphql_type when using inheritance

---

Gemfile.lock
lib/graphql_rails/version.rb

I managed to break V1.2.5 release. I released it too early to rubygems and then removed it. Then tried to release again, but rubygems does not allow to release same version twice. So I'm creating V1.2.6 release with same code as in `v1.2.5`

Bump version V1.2.6

---

CHANGELOG.md
docs/other_tools/schema_dump.md
lib/graphql_rails/router/route.rb
lib/graphql_rails/tasks/dump_graphql_schema.rb
lib/graphql_rails/tasks/dump_graphql_schemas.rb
lib/graphql_rails/tasks/schema.rake
spec/lib/graphql_rails/tasks/dump_graphql_schema_spec.rb
spec/lib/graphql_rails/tasks/dump_graphql_schemas_spec.rb

When project has multiple schemas, it's becomes annoying to update them only-by-one. This PR adds multiple group names support for `graphql_rails:schema:dump` rake task, so now we dump all schemas by default or we can specify specific multiple dumps like this:
`rake graphql_rails:schema:dump["group1, group2, ..., group99"]`

Allow dumping multiple schemas

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/attributable.rb
lib/graphql_rails/attributes/attribute_name_parser.rb
spec/lib/graphql_rails/controller/action_configuration_spec.rb

In most cases, predicate methods return only `true` or `false` values, but by default `GraphqlRails` sets this type to `Boolean` which indicates that value might be `null` too.
```ruby
graphql do |c|
c.attribute(:enabled?) # sets `Boolean` type based on name
end
```
This PR changes this default value to always be non-nullable:
```ruby
graphql do |c|
c.attribute(:enabled?) # sets `Boolean!` type based on name
end
```

Change default predicate method type to be non-nullable

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/attributable.rb
lib/graphql_rails/attributes/attribute.rb
lib/graphql_rails/attributes/attribute_configurable.rb
lib/graphql_rails/attributes/input_attribute.rb
lib/graphql_rails/concerns/chainable_options.rb
lib/graphql_rails/input_configurable.rb
lib/graphql_rails/model/configurable.rb
lib/graphql_rails/model/configuration.rb
lib/graphql_rails/model/input.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb
spec/lib/graphql_rails/attributes/input_attribute_spec.rb
spec/lib/graphql_rails/model/graphql_input_type_builder_spec.rb

Currently it's possible to define graphql.attribute in a chainable way like this:
```ruby
graphql do |c|
c.attribute(:first_name)
.type(:string!)
.description('...')
end
```
but this does not work with input attributes. This makes graphql attribute behavior inconsistent.
This PR adds chainable syntax support for `graphql.input.attribute`, so this will be also possible:
```ruby
graphql.input do |c|
c.attribute(:first_name)
.type(:string!)
.description('...')
end
```

Make input attributes chainable

---

CHANGELOG.md
lib/graphql_rails/attributes/type_parser.rb
spec/lib/graphql_rails/attributes/type_parser_spec.rb

It's almost impossible to understand where is the issue when the `NotSupportedFeature` error is raised without any hint to type. This PR includes type name in error message

Include type name when raising error for types without pagination support

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/attribute_name_parser.rb
lib/graphql_rails/attributes/input_type_parser.rb
lib/graphql_rails/attributes/type_parseable.rb
lib/graphql_rails/attributes/type_parser.rb
lib/graphql_rails/model/find_or_build_graphql_type.rb
spec/lib/graphql_rails/attributes/input_type_parser_spec.rb
spec/lib/graphql_rails/attributes/type_parser_spec.rb
spec/lib/graphql_rails/model/find_or_build_graphql_type_spec.rb

This improvement allows defining graphql-ruby types dynamically using string:
before this change:
```ruby
class User
include GraphqlRails::Model
graphql.attribute(:required_list_of_dates)
.type(::GraphQL::Types::ISO8601Date.to_non_null_type.to_list_type.to_non_null_type)
end
```
after change:
```ruby
class User
include GraphqlRails::Model
graphql.attribute(:required_list_of_dates)
.type('[::GraphQL::Types::ISO8601Date!]!')
end
```

Allow dynamically defining graphql-ruby types

---

.rubocop.yml
CHANGELOG.md
lib/graphql_rails/decorator/relation_decorator.rb
spec/lib/graphql_rails/decorator/relation_decorator_spec.rb

Currently decorated relation misses some methods quite often used with ActiveRecord relations. This PR adds additional methods:
```ruby
SomeDecorator.decorate(relation).find(1) # returns SomeDecorator instance
SomeDecorator.decorate(relation).find_by(1) # returns SomeDecorator instance or nil
SomeDecorator.decorate(relation).empty? # delegates to relation#empty?
```
**before**
```ruby
it 'returns empty list' do
expect(request.result.to_a).to be_empty
end
```
**after**
```ruby
it 'returns empty list' do
expect(request.result).to be_empty
end
```
**before**
since there is no `find_by` support, we need to hack using `where(id: 1).first`
and there is no easy way for hacking `find` :(
```ruby
SomeDecorator.decorate(relation).find(1) # raises no method error …
```

Add more methods to relation decorator

---

CHANGELOG.md
lib/graphql_rails/attributes/type_parseable.rb
spec/lib/graphql_rails/attributes/type_parser_spec.rb

Currently, we have a bug when referencing attribute type as a string and that type is defined as graphql-ruby enum such as this:
```ruby
class ColorsEnum < BaseEnum
value 'RED', value: :red
value 'BLUE', value: :blue
end
```
before:
```ruby
class SomeModel
graphql.attribute(:colors).type('[ColorsEnum!]!') # raises GraphqlRails::Attributes::TypeParseable::UnknownTypeError: Type "[ColorsEnum!]!" is not supported...
end
```
after:
```ruby
class SomeModel
graphql.attribute(:colors).type('[ColorsEnum!]!') # all good!
end
```

Allow to define graphql-ruby enum classes as strings

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/type_parseable.rb
spec/lib/graphql_rails/attributes/type_parseable_spec.rb

Adds aliases for some frequently used not-so-standard graphql types
```ruby
class Foo
include GraphqlRails::Model
graphql do |c|
c.attribute(:blocked_from).type(:date)
c.attribute(:data).type(:json)
c.attribute(:updated_at).type(:datetime)
end
end
```
Keep in mind that this PR introduces breaking change. Previously `date` was an alias for `String` and now it's changed to `GraphQL::Types::ISO8601Date!`. Since this was not documented, I assume that it's quite safe to change it.
Solves https://github.com/samesystem/graphql_rails/issues/92

Add aliases for common graphql-graphql types

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/attribute.rb
lib/graphql_rails/attributes/attribute_configurable.rb
lib/graphql_rails/attributes/input_attribute.rb
lib/graphql_rails/controller/build_controller_action_resolver/controller_action_resolver.rb
lib/graphql_rails/model/build_graphql_input_type.rb
lib/graphql_rails/model/find_or_build_graphql_type_class.rb
lib/graphql_rails/query_runner.rb
lib/graphql_rails/tasks/dump_graphql_schema.rb
lib/graphql_rails/types/argument_type.rb
lib/graphql_rails/types/field_type.rb
lib/graphql_rails/types/hidable_by_group.rb
lib/graphql_rails/types/object_type.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb
spec/lib/graphql_rails/attributes/input_attribute_spec.rb
spec/lib/graphql_rails/tasks/dump_graphql_schema_spec.rb

This feature allows limiting field visibility only for certain groups. Works similar as `groups` in router, but on attribute level. Works with input attributes (arguments) too.
Solves https://github.com/samesystem/graphql_rails/issues/119

Add groups to models

---

CHANGELOG.md
lib/graphql_rails/attributes/type_parseable.rb
spec/lib/graphql_rails/attributes/type_parser_spec.rb

Currently, it's impossible to set stringified type for graphql-ruby input type. This PR fixes that issue and prevents similar issues from happening in the future.
**before** 
```ruby
class User
graphql.attribute(:data).type('Types::DataInputType!') # raises error
end
```
**after** 
```ruby
class User
graphql.attribute(:data).type('Types::DataInputType!') # no error
end
```

Allow any graphql member object to be used in stringified form

---

lib/graphql_rails/router/schema_builder.rb
spec/lib/graphql_rails/router_spec.rb

Query type must always be defined to allow doing schema introspection.

Refs #229: Always define query type to allow introspection

---

CHANGELOG.md
docs/components/routes.md
lib/graphql_rails/router.rb
lib/graphql_rails/router/build_schema_action_type.rb
lib/graphql_rails/router/route.rb
lib/graphql_rails/router/schema_builder.rb
spec/lib/graphql_rails/router/build_schema_action_type_spec.rb
spec/lib/graphql_rails/router_spec.rb
spec/support/dummy_app/controllers/dummy/users_controllers.rb
spec/support/dummy_app/dummy.rb
spec/support/dummy_app/models/dummy/user.rb

This PR adds two new router features: `namespace` and `scope`. It allows to nest actions (action can be deep nested too). Here is an example:
```ruby
query :user, to: 'users#show'  # triggers users_controller
scope :top_secret do
query :user, to: 'top_secret_users#show'  # triggers top_secret_users_controller
end
namespace :admin do
query :user, to: 'users#show' # triggers admin/users_controller
end
```
on graphql it can be accessed like this:
```graphql
query {
user(id: '1') { ... } # triggers users_controller
topSecret {
user(id: '1') { ... } # triggers top_secret_users_controller
}
admin {
user(id: '1') { ... }  # triggers admin/users_controller
}
}
```
solves: https://github.com/samesystem/graphql_rails/issues/53

Add namespaces and scope prefixes

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/attribute.rb
lib/graphql_rails/attributes/attribute_configurable.rb
lib/graphql_rails/attributes/input_attribute.rb
lib/graphql_rails/types/hidable_by_group.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb
spec/lib/graphql_rails/attributes/input_attribute_spec.rb
spec/lib/graphql_rails/types/hidable_by_group_spec.rb

This PR adds an attribute option called `hidden_in_groups`. As the name suggests, it makes field hidden in given groups.
Example:
```ruby
class User
graphql do |c|
c.attribute(:id).type('ID!').hidden_in_groups(:my_secret_group)
end
end
```

Add `hidden_in_groups` option for attributes

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/attribute.rb
lib/graphql_rails/attributes/attribute_configurable.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb

Adds `extras` option which allows to turn on features such as `lookahead`:
```ruby
class User
graphql do |c|
c.attribute(:orders).extras([:lookahead])
end
def orders(lookahead:)
end
end
```

Add `extras` config for attribute

---

CHANGELOG.md
lib/graphql_rails/controller/request.rb
lib/graphql_rails/router/route.rb
spec/lib/graphql_rails/controller/request_spec.rb

This PR allows accessing lookahead data in graphql controller:
```ruby
class UsersController < GraphqlController
model('User')
action(:show).returns_single
def show
users = User.all
users = users.includes(:orders) if graphql_request.lookahead.selects?(:orders)
users.find(params[:id])
end
end
```

Include lookahead in controller

---

lib/graphql_rails/rspec_controller_helpers.rb

We added `lookahead` data into the graphql_request object so you can access it from the controller. However, rspec helper was not updated, and in tests `graphql_request.lookahead` returns `nil` which does not happen in the actual controller. 
This PR adds a dummy lookahead instance to request which makes graphql_controller specs a bit more similar to the real-life cases.

Include dummy lookahead data into controller specs

---

lib/graphql_rails/router.rb
lib/graphql_rails/router/schema_builder.rb

Currently we can not pass options to `use` as the method defined dynamically does not accept keyword arguments.

Pass kwargs to methods such as "use" on graphql router/schema

---

.github/workflows/ruby.yml
spec/spec_helper.rb

This is an alternate version of my PR #261.  That PR had Ruby 2.7 failing, which appears to be a result of one of the dependency upgrades.  As those dependency upgrades aren't needed for the core changes - adding Ruby 3.2, upgrading the checkout action so that CI can continue to run, I rebuilt the PR without that.
Aside from code coverage, everything runs green on my fork.
cc: @povilasjurcys

Add Ruby 3.2 to CI, Upgrade Checkout Action - v2

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/attribute.rb
lib/graphql_rails/attributes/attribute_configurable.rb
lib/graphql_rails/attributes/input_attribute.rb
spec/lib/graphql_rails/attributes/input_attribute_spec.rb

This PR enables to add alias key to input attributes. This is handy during refactoring.
After this change:
```ruby
class Post
include GraphqlRails::Model
graphql.input do |c|
c.attribute(:author_id).type('ID').property(:user_id)
end
end
```
```gql
mutation createPost(input: { authorId: 123 }) {
author
}
```
Will pass `user_id` instead of `authorId` in controller:
```ruby
def create
params[:input] # => { user_id: 123 }
end
```

Add input attribute aliases

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/attribute_configurable.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb
spec/lib/graphql_rails/attributes/input_attribute_spec.rb

Copying attribute values from one attribute to another can be useful in certain situations. For instance, when you need to create alias methods or multiple input types that are similar. 
This pull request introduces a new method called `Attribute#same_as` that allows you to perform this operation.

Add same_as attribute method

---

lib/graphql_rails/attributes/attributable.rb
lib/graphql_rails/attributes/attribute_configurable.rb
spec/lib/graphql_rails/attributes/attribute_spec.rb
spec/lib/graphql_rails/attributes/input_attribute_spec.rb

Currently, we have a bug when using `same_as` with the attribute that has a cached name (this happens, when we call `attribute.name`). As a result, the new attribute will inherit the name. This is incorrect. 
This PR improves the code, so the new attribute will have its own name even if the `same_as` attribute has cached the name

Fix same_as attribute name handling

---

CHANGELOG.md
docs/components/controller.md
lib/graphql_rails/attributes/attribute.rb
lib/graphql_rails/router/route.rb
spec/lib/graphql_rails/controller/configuration_spec.rb
spec/lib/graphql_rails/router/route_spec.rb

The previous fix fixed only the `max_page_size` bug. This PR fixes any other possible pagination option passing.

Add support for more pagination options and add missing documentation

---

CHANGELOG.md
lib/graphql_rails/model/find_or_build_graphql_input_type.rb
lib/graphql_rails/model/find_or_build_graphql_type.rb
spec/lib/graphql_rails/model/input_spec.rb

Currently, graphql crashes when we use nested input types. This PR fixes the issue

Do not crash when using deeply nested input definitions

---

CHANGELOG.md
lib/graphql_rails/controller.rb
lib/graphql_rails/controller/configuration.rb
lib/graphql_rails/controller/handle_controller_error.rb
spec/lib/graphql_rails/controller/handle_controller_error_spec.rb
spec/lib/graphql_rails/controller_spec.rb

This PR allows handling graphql errors using `rescue_from` hook same way as in RoR controllers:
```ruby
class MyController < GraphqlRails::Controller
rescue_from MyError, with:  :custom_handle
private
def custom_handle(error)
render error: "custom_error: #{error.message)"
end
end
```

Add `rescue_from` support in controllers

---

CHANGELOG.md
docs/components/model.md
lib/graphql_rails/attributes/type_parseable.rb
lib/graphql_rails/model/configuration.rb
lib/graphql_rails/model/find_or_build_graphql_type.rb
lib/graphql_rails/model/find_or_build_graphql_type_class.rb
spec/lib/graphql_rails/attributes/type_parser_spec.rb
spec/lib/graphql_rails/model/configuration_spec.rb
spec/lib/graphql_rails/model/find_or_build_graphql_type_class_spec.rb
spec/lib/graphql_rails/model/find_or_build_graphql_type_spec.rb

This PR adds basic interface support for GraphqlRails::Model.
Usage:
```ruby
module VisitorInterface
include GraphQL::Schema::Interface
field :failed_logins_count, Integer
end
class UserDecorator
include GraphqlRails::Model
graphql do |c|
c.implements(VisitorInterface)
end
end
```

Add `implements` support for models

---

CHANGELOG.md
lib/graphql_rails/controller/log_controller_action.rb
lib/graphql_rails/rspec_controller_helpers.rb
spec/lib/graphql_rails/rspec_controller_helpers_spec.rb

Added `controller` and `action_name` methods to `Response` object which is used in RSpec tests only. I do not expect it to be used widely but it should be quite useful for other tools such as graphql type validators I'm working on here: https://github.com/povilasjurcys/rspec-extra_matchers

Include controller and action name in response when using RSpecControllerHelpers

---

.github/workflows/ruby.yml
CHANGELOG.md

Some libraries that we use no longer support ruby 2.7. For this reason we can't get newest security updates. This PR drops ruby 2.7 support

Stop supporting ruby<3.0.0

---

CHANGELOG.md
Gemfile.lock
lib/graphql_rails/version.rb

Updates graphql_rails version to 3.0.0. The major version was updated because of backward compatibility issues: we stopped supporting ruby 2.7.

Bump version to 3.0.0

---

CHANGELOG.md
lib/graphql_rails/controller.rb
lib/graphql_rails/controller/action_hooks_runner.rb
lib/graphql_rails/controller/request.rb
spec/lib/graphql_rails/controller/action_hooks_runner_spec.rb
spec/lib/graphql_rails/controller_spec.rb

The controller processes the action even though a hook renders the error. This is incorrect.
This PR fixes the issue by stopping processing the action if an error is present.

Better handle render in controller hooks

---

CHANGELOG.md
docs/components/decorator.md
lib/graphql_rails/decorator.rb
lib/graphql_rails/decorator/relation_decorator.rb
spec/lib/graphql_rails/decorator_spec.rb

This PR allows to customize how decorator instances are build. This allows more advanced strategies or building decorators from multiple objects

Allow passing custom decorator build strategy

---

lib/graphql_rails/concerns/service.rb
lib/graphql_rails/model/add_fields_to_graphql_type.rb
lib/graphql_rails/model/call_graphql_model_method.rb
lib/graphql_rails/model/direct_field_resolver.rb
lib/graphql_rails/router.rb
spec/lib/graphql_rails/concerns/service_spec.rb
spec/lib/graphql_rails/model/direct_field_resolver_spec.rb

Reduces object allocations by improving the way attributes are resolved. On massive collections (where each item essentially has same attributes) this will yield to around 20% less object allocations.

Reduce memory allocations when defining attributes
