samesystem/graphql_rails

- .rubocop.yml
- docs/components/controller.md
- lib/graphql_rails/controller.rb
- lib/graphql_rails/controller/before_action_filter.rb
- lib/graphql_rails/controller/configuration.rb
- spec/lib/graphql_rails/controller/before_action_filter_spec.rb
- spec/lib/graphql_rails/controller/configuration_spec.rb
- spec/lib/graphql_rails/controller_spec.rb
> Add `only` and `except` params to `Controller.before_action`

- Gemfile.lock
- docs/components/controller.md
- graphql_rails.gemspec
- lib/graphql_rails/controller.rb
- lib/graphql_rails/controller/action_configuration.rb
- lib/graphql_rails/controller/action_hook.rb
- lib/graphql_rails/controller/action_hooks_runner.rb
- lib/graphql_rails/controller/configuration.rb
- lib/graphql_rails/version.rb
- spec/lib/graphql_rails/controller/action_hook_spec.rb
- spec/lib/graphql_rails/controller/action_hooks_runner_spec.rb
- spec/lib/graphql_rails/controller/configuration_spec.rb
- spec/lib/graphql_rails/controller_spec.rb
- spec/lib/graphql_rails/router_spec.rb
This PR includes:
* refactoring - renamed `action_filters` to `action_hooks` to reduce confusion
* enhancement - now it's possible to add action hooks without name (anonymous hooks)
* bugfix: around hooks now will not override return value
* bugfix: controller classes will not share action configuration when inherited
> Various small improvements

- CHANGELOG.md
- lib/graphql_rails/router/plain_cursor_encoder.rb
- lib/graphql_rails/router/schema_builder.rb
> Do not convert paginated response cursor to Base64

- CHANGELOG.md
- lib/graphql_rails/controller.rb
> Always underscore controller params

- CHANGELOG.md
- lib/graphql_rails/controller.rb
- lib/graphql_rails/controller/configuration.rb
- lib/graphql_rails/rspec_controller_helpers.rb
- spec/lib/graphql_rails/rspec_controller_helpers_spec.rb
Fixes #58 and makes easier to implement #46
> User real schema in tests

- CHANGELOG.md
- docs/components/routes.md
- lib/graphql_rails/router/resource_routes_builder.rb
- spec/lib/graphql_rails/router/plain_cursor_encoder_spec.rb
- spec/lib/graphql_rails/router_spec.rb
> Allow to append resource action name to the end of field name

- lib/graphql_rails/concerns/service.rb
- lib/graphql_rails/controller/log_controller_action.rb
- lib/graphql_rails/model/build_enum_type.rb
- lib/graphql_rails/model/build_graphql_input_type.rb
- lib/graphql_rails/model/build_graphql_type.rb
- lib/graphql_rails/model/configuration/count_items.rb
Service module was included in order to make code more DRY
> Refactor code to reduce duplication

- CHANGELOG.md
- docs/components/controller.md
- lib/graphql_rails/controller/action_configuration.rb
- lib/graphql_rails/controller/configuration.rb
- spec/lib/graphql_rails/controller/action_configuration_spec.rb
- spec/lib/graphql_rails/controller/configuration_spec.rb
> Add default_action and default model for controller

- docs/components/controller.md
- lib/graphql_rails/controller.rb
- lib/graphql_rails/controller/configuration.rb
- spec/lib/graphql_rails/controller/configuration_spec.rb
> Rename default_action to action_default

- lib/generators/graphql_rails/install_generator.rb
- lib/generators/graphql_rails/templates/graphql_schema.erb
- lib/generators/graphql_rails/templates/graphql_schema_spec.erb
- lib/generators/graphql_rails/templates/initializer.erb
- lib/graphql_rails.rb
- lib/graphql_rails/railtie.rb
- lib/graphql_rails/router.rb
- lib/graphql_rails/tasks/schema.rake
what was changed:
* removed initializer
* moved router to `app/graphql/graphql_schema.rb`
* added graphql schema snapshot tests
* added schema dump rake task
> Improve install generators

- docs/components/controller.md
- lib/graphql_rails/controller.rb
- lib/graphql_rails/controller/request.rb
- lib/graphql_rails/controller/request/format_errors.rb
- lib/graphql_rails/errors/custom_execution_error.rb
- lib/graphql_rails/errors/execution_error.rb
- lib/graphql_rails/errors/system_error.rb
- lib/graphql_rails/errors/validation_error.rb
- spec/lib/graphql_rails/controller/request/format_errors_spec.rb
- spec/lib/graphql_rails/controller_spec.rb
> Improve errors

- lib/graphql_rails/attributes/input_attribute.rb
- lib/graphql_rails/input_configurable.rb
- lib/graphql_rails/model/input.rb
- spec/lib/graphql_rails/attributes/input_attribute_spec.rb
> Remove unused code

- lib/graphql_rails/model/build_enum_type.rb
- spec/lib/graphql_rails/model/build_enum_type_spec.rb
> Show human friendly errors when enum has wrong setup

- lib/graphql_rails/controller/configuration.rb
- lib/graphql_rails/router/resource_routes_builder.rb
- spec/lib/graphql_rails/router_spec.rb
> Do not crash when using camelized action or route name

- docs/README.md
- docs/components/controller.md
- docs/components/model.md
A couple spelling fixes in the documentation
> Better spelling in docs

- .rubocop.yml
- CHANGELOG.md
- lib/graphql_rails/model/call_graphql_model_method.rb
- spec/lib/graphql_rails/integration_tests/model_arguments_spec.rb
- spec/lib/graphql_rails/model/call_graphql_model_method_spec.rb
- spec/spec_helper.rb
> Convert field input arguments to hash

- CHANGELOG.md
- lib/graphql_rails/controller/log_controller_action.rb
Closes #172 
Tested on Rails 6.1 app and Rails 6.0.3.4 app.
> Fixed usage with Rails 6.1

- .github/workflows/ruby.yml
- .travis.yml
Isolated changes from #191 
Would be nice to revive this projects CI at least.
> Create spec workflow

- Gemfile.lock
- spec/lib/graphql_rails/router_spec.rb
Fixes failing spec and still checks if handler was created
> Fix router specs for error handler check

- docs/components/model.md
- lib/graphql_rails/attributes/input_attribute.rb
- spec/lib/graphql_rails/attributes/input_attribute_spec.rb
> Add default value option

- Gemfile.lock
- graphql_rails.gemspec
- lib/graphql_rails/attributes/input_attribute.rb
- lib/graphql_rails/attributes/type_parseable.rb
- lib/graphql_rails/controller/build_controller_action_resolver/controller_action_resolver.rb
- lib/graphql_rails/decorator/relation_decorator.rb
- spec/lib/graphql_rails/attributes/input_attribute_spec.rb
- spec/lib/graphql_rails/attributes/input_type_parser_spec.rb
- spec/lib/graphql_rails/attributes/type_parser_spec.rb
- spec/lib/graphql_rails/controller_spec.rb
- spec/lib/graphql_rails/router_spec.rb
Initial change to get 2.0.* working. There will likely be more things left which is not yet working, but this gets the tests passing and subscriptions working.
> Update graphql ruby to 2.0.21. Support subscriptions

- CHANGELOG.md
- lib/graphql_rails/attributes/attribute.rb
- lib/graphql_rails/controller/action.rb
- lib/graphql_rails/controller/build_controller_action_resolver.rb
- lib/graphql_rails/router/route.rb
- spec/lib/graphql_rails/attributes/attribute_spec.rb
- spec/lib/graphql_rails/controller/action_spec.rb
- spec/lib/graphql_rails/controller/build_controller_action_resolver_spec.rb
- spec/lib/graphql_rails/router/route_spec.rb
This PR fixes the issue https://github.com/samesystem/graphql_rails/issues/154. Until now, the custom `max_page_size` was ignored
> Take into account max_page_size for paginated fields

- CHANGELOG.md
- Gemfile.lock
- graphql_rails.gemspec
Bumping graphql version to the most recent one.
> Bump graphql version to 2.1.7

- lib/graphql_rails/attributes/attributable.rb
- lib/graphql_rails/model/configuration.rb
- spec/lib/graphql_rails/model_spec.rb
Inheriting type doesn't allow overriding field types
This PR fixes it
> Fix inheritance support

- lib/graphql_rails/router.rb
Adds `tracer` method to router
> Add tracer to router
